### PR TITLE
Fixed replacement of basePath at the beginnings of URLs

### PR DESCRIPTION
**Pull request by kantord**

### CODE REVIEW

**Comment by naz** [comment]
Hey @kantord . Can you please expand on what usecase you are trying to solve with this change? Cheers!

**Comment by kantord** [comment]
Hi @naz, thanks for the quick reply.

It's 2 things:

- Fixes a bug with base paths. Before the fix, based paths were removed even from the middle of URLs, for example if the base path is '/foo/' then '/api/bar/foo/baz/' was normalized to '/api/bar/baz' which is a bug
- It adds support for servers https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by kantord** [comment]
I realized this is probably a mistake on my part. I realized this package is only meant to support OpenAPI v2.0, so probably servers support is not revelant here. If you want, I can remove the servers support part and only push the bugfix

**Comment by naz** [comment]
Yeah, just the bugfix would be ideal. Thanks @kantord

**Comment by kantord** [comment]
Cool, now it's just the bugfix, @naz :wink:

**Pull request merged**
